In [14]:
import pandas as pd

df = pd.read_excel("Stock.xlsx",index_col="Name")
df.sort_index(ascending=False)

                             Category  Price  Amount
Name
ไมโครโฟน              เครื่องใช้ไฟฟ้า    750       1
โซฟา                     เฟอร์นิเจอร์   5000       5
โคมไฟ                เครื่องใช้ในบ้าน   1200       7
เสื้อยืดคอกลม                เสื้อผ้า    500       2
เมาส์              อุปกรณ์คอมพิวเตอร์    900      10
เครื่องซักผ้า         เครื่องใช้ไฟฟ้า   3500       0
รถบังคับ                      ของเล่น    500       6
ยางลบ                 อุปกรณ์การเรียน     20       5
ปากกา                 อุปกรณ์การเรียน    200       5
ทีวี                  เครื่องใช้ไฟฟ้า  15000       7
ตุ๊กตาหมีพูห์                 ของเล่น    950       5
จาน                       เครื่องครัว    250       4
คีย์บอร์ด          อุปกรณ์คอมพิวเตอร์    850       5
กางเกงยีนต์                  เสื้อผ้า    999       8
External HardDisk  อุปกรณ์คอมพิวเตอร์   2500       7

In [17]:
df.sort_values("Price",ascending=False,inplace=True)
df

                             Category  Price  Amount
Name
ทีวี                  เครื่องใช้ไฟฟ้า  15000       7
โซฟา                     เฟอร์นิเจอร์   5000       5
เครื่องซักผ้า         เครื่องใช้ไฟฟ้า   3500       0
External HardDisk  อุปกรณ์คอมพิวเตอร์   2500       7
โคมไฟ                เครื่องใช้ในบ้าน   1200       7
กางเกงยีนต์                  เสื้อผ้า    999       8
ตุ๊กตาหมีพูห์                 ของเล่น    950       5
เมาส์              อุปกรณ์คอมพิวเตอร์    900      10
คีย์บอร์ด          อุปกรณ์คอมพิวเตอร์    850       5
ไมโครโฟน              เครื่องใช้ไฟฟ้า    750       1
เสื้อยืดคอกลม                เสื้อผ้า    500       2
รถบังคับ                      ของเล่น    500       6
จาน                       เครื่องครัว    250       4
ปากกา                 อุปกรณ์การเรียน    200       5
ยางลบ                 อุปกรณ์การเรียน     20       5

In [18]:
df["delivery"]=100

In [20]:
df["total"]=df["Price"]+df["delivery"]
df

                             Category  Price  Amount  delivery  total
Name
ทีวี                  เครื่องใช้ไฟฟ้า  15000       7       100  15100
โซฟา                     เฟอร์นิเจอร์   5000       5       100   5100
เครื่องซักผ้า         เครื่องใช้ไฟฟ้า   3500       0       100   3600
External HardDisk  อุปกรณ์คอมพิวเตอร์   2500       7       100   2600
โคมไฟ                เครื่องใช้ในบ้าน   1200       7       100   1300
กางเกงยีนต์                  เสื้อผ้า    999       8       100   1099
ตุ๊กตาหมีพูห์                 ของเล่น    950       5       100   1050
เมาส์              อุปกรณ์คอมพิวเตอร์    900      10       100   1000
คีย์บอร์ด          อุปกรณ์คอมพิวเตอร์    850       5       100    950
ไมโครโฟน              เครื่องใช้ไฟฟ้า    750       1       100    850
เสื้อยืดคอกลม                เสื้อผ้า    500       2       100    600
รถบังคับ                      ของเล่น    500       6       100    600
จาน                       เครื่องครัว    250       4       100    350
ปากกา                 อุปกรณ์การเรียน    200       5       100    300
ยางลบ                 อุปกรณ์การเรียน     20       5       100    120